# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: AR FaceFighter - The Most Addictive AR Game for iPhone X
email: hello@codeandco.com
description: >- # this means to ignore newlines until "baseurl:"
  AR FaceFighter – The addictive AR game for iPhone X. Produced by code & co. at ww.codeandco.com.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.facefighterapp.com" # the base hostname & protocol for your site, e.g. http://example.com

# custom page settings
google_analytics_container_id: UA-75779488-7
google_site_verification:

canonical: http://www.facefighterapp.com

og_image: facefighter_og.png
og_url: http://www.facefighterapp.com

twitter_site:
twitter_creator:
twitter_image: facefighter_tw.png
twitter_alt: AR FaceFighter - The Most Addictive AR Game for iPhone X

appStoreLink: https://itunes.apple.com/de/app/ar-facefighter/id1363494526?mt=8
playStoreLink:

app_id: 1363494526

show_logo: false
primary_cta_label:

show_app_icon: true
app_icon_alignment: text-center

title_line_1: Your Face is
title_line_2: the Controller.
title_alignment: text-center

subtitle: The addictive AR game for iPhone X.
subtitle_alignment: text_center

description:
description_alignment:

features_list:
#  - icon:
#    icon_alt:
#    text:

impressum_link: https://www.codeandco.com/impressum/
terms_link: https://www.codeandco.com/terms/
privacy_notice_link: https://www.codeandco.com/privacy-notice/
contact_link: https://www.codeandco.com/contact/

# if custom navigation:
main_nav:
  - title:
    url:


# Build settings
markdown: kramdown

plugins:
  - jekyll-feed


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - gulpfile.js
  - package.json
  - scss
  - .DS_Store
  - .idea
